import { Hero } from './hero';

export const HEROES: Hero[] = [
  { id: 11, name: 'Dr Strange', description: 'Hechicero supremo y guardián de la gema del tiempo', faction: 'Avenger', image: 'https://static1.comicvine.com/uploads/original/11125/111253442/5262851-pyro.jpg' },
  { id: 12, name: 'Namor', description: 'Hijo de un mutante y una reina atlante, actual rey de Atlantis', faction: 'Atlantis', image: 'https://static1.comicvine.com/uploads/original/11125/111253442/5262851-pyro.jpg' },
  { id: 13, name: 'Iron Man', description: 'Porpietario de industrias Stark y actual miembro de los Vengadores, usa una armadura con un reactor que a parte de darle energía para combatir, le ayuda a sobrevivir a las esquirlas metálicas que tiene acercandose a su corazón.', faction: 'Avenger', image: 'https://static1.comicvine.com/uploads/original/11125/111253442/5262851-pyro.jpg' },
  { id: 14, name: 'Capitana Marvel', description: 'Expiloto humana criada como kree con poderes concedidos por el cubo cósmico', faction: 'Kree', image: 'https://static1.comicvine.com/uploads/original/11125/111253442/5262851-pyro.jpg' },
  { id: 15, name: 'Magneto', description: 'Líder mutante de la hermandad, opositores a la raza humana. Tiene el poder de controlar cualquier elemento metálico a su antojo', faction: 'Brotherhood', image: 'https://static1.comicvine.com/uploads/original/11125/111253442/5262851-pyro.jpg' },
  { id: 16, name: 'Wasp', description: 'Compañera de Hanq Pym, creadores de las partículas Pym capaces de hacerte cambiar de tamaño', faction: 'Pym Tecnologies', image: 'https://static1.comicvine.com/uploads/original/11125/111253442/5262851-pyro.jpg' },
  { id: 17, name: 'Capitán América', description: 'Supero soldado creado con un suero para ganar la segunda guerra mundial y líder de los vengadores', faction: 'Avenger', image: 'https://static1.comicvine.com/uploads/original/11125/111253442/5262851-pyro.jpg' },
  { id: 18, name: 'Mr. Fantastic', description: 'Líder de los cuatro fantásticos con el poder de estirar su cuerpo sin límites', faction: 'Fantastic Four', image: 'https://static1.comicvine.com/uploads/original/11125/111253442/5262851-pyro.jpg' },
  { id: 19, name: 'Pyro', description: 'Antiguo miembro de x-men, actual miembro de la Hermandad, muy fiel a Magneto', faction: 'Brotherhood', image: 'https://static1.comicvine.com/uploads/original/11125/111253442/5262851-pyro.jpg' },
  { id: 20, name: 'Thanos', description: 'El líder de la orden negra y titán loco, capaz de sostener las gemas del infinito', faction: 'Black Order', image: 'https://i2.wp.com/www.comicsbeat.com/wp-content/uploads/2012/09/Marvels-supervillain-Thanos-gets-his-due-3U1PQ6NN-x-large.jpg?fit=490%2C360&ssl=1' }
];