version: "3.9"
services:
  mongodbHeroeverse:
    image: mongo:4.0.4
    volumes:
      - ./heroeverse/database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
      - "27017:27017"
  heroverse:
    image: saulalonso2/heroeverse:1.0
    ports:
      - "4000:4000"